# This file was generated by GoReleaser. DO NOT EDIT.
cask "nesly" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "b29bf0b87d43955d3d85033b8d70926a07caf7dc5e9bf9c81afc44bd2edabdd8"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ee437e44e2592f371588504d30bacaae66f6253b9979ca8e62f48be66217eda4"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "16ad875e7a7995dcdf3a40439b902f617b429178274b48fa0f30861674121465"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "20e1e55769a1ec204d6efce2e1cec5471ad47c9a080cdba8fd46f9809e7c40be"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nesly"
  desc "Deploy applications to nesly from your terminal"
  homepage "https://nesly.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nesly"

  # No zap stanza required
end
