# This file was generated by GoReleaser. DO NOT EDIT.
cask "nesly" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "19cfcf3af1b847989c7ca7c8b62d232c0d08d9641b71f8d693543a3eea1938d4"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b71837cb37565f820bf46faf01c7603289cc6957f775601ecc4d41e129d9882"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fa621515f3b16c46ba2a3457ff86689d6a77773a08fe48405befeeb324dde15d"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d0cc3968d5f633ab6b007d11e112c06409b995906f356a6ac1a51bdc5b53bf9"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nesly"
  desc "Deploy applications to nesly from your terminal"
  homepage "https://nesly.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nesly"

  # No zap stanza required
end
