# This file was generated by GoReleaser. DO NOT EDIT.
cask "nesly" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "b0e0d0fe0db34d48639276c72a41fe6b390d44d86455af30818036810a5c8798"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "32b73595c7fc798bf266ae4db0328abe56dc66db00d1599ec57d1f71409f5b37"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "79f3837e6f8124b45d185b5eb0fe1ae880cd3d1afb7205a172447cd3bfe8339c"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6856a58f952691f8ba1208f0e02bfde414026f79f30af56fe47e56796d2047fe"
      url "https://github.com/neslyhq/nesly/releases/download/v#{version}/nesly_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nesly"
  desc "Deploy applications to nesly from your terminal"
  homepage "https://nesly.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nesly"

  # No zap stanza required
end
